name: Run test via Pkg.test()

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  vanilla-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
      # - uses: julia-actions/julia-buildpkg@v1
      # - uses: julia-actions/julia-runtest@v1
      - run: |
          using Pkg
          Pkg.activate(".")
          Pkg.develop(path="lib/EventTrackerBase")
          Pkg.test()
        shell: julia {0}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: Pkg.test
          name: codecov-umbrella
